services:
  # This is a dummy mysql server
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - local-mysql-env
    volumes:
      - mysqlDataDir:/var/lib/mysql
    ports:
      - 3306:3306
  demo:
    image: sp_mysql_demo
    env_file:
      - local-env
    ports:
      - 8080:80

volumes:
  mysqlDataDir: