services:
  # This is a dummy mysql server
  mysql:
    image: mysql
    env_file:
      - local-mysql-env
    volumes:
      - mysqlDataDir:/var/lib/mysql
    ports:
      - 3306:3306
  demo:
    image: sp_mysql_demo
    env_file:
      - local-env
    ports:
      - 80:8080

volumes:
  mysqlDataDir: