apiVersion: apps/v1
kind : Deployment
metadata:
  name: sp-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sp-app
  template:
    metadata:
      labels:
        app: sp-app
    spec:
      containers:
        - name: sp-service-container
          image: sp_mysql_demo
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_HOST
              value: "mysql-service.default"
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: Test@1234
